### ISSUE TITLE
Dataset record: add new attribute for EDA sites: isPublic, with values private and public based on isPublic property

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EbrcModelCommon#18]
based on client PR https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/119
for issue https://github.com/VEuPathDB/web-eda/issues/822

**Comment by danicahelb** [comment]
@dmfalke how should the outreach team QA this?

**Comment by dmfalke** [comment]
Oh, sorry, I meant to change the status to completed. There isn't anything to qa.
