### ISSUE TITLE
Implement isSecret property to hide study card from the live & legacy sites

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EbrcModelCommon#22]
The grayed-out study card for UMSP should not be visible on our live site. We still want UMSP available on the QA and QA.restricted sites.

We decided against commenting out the injector for UMSP on the branch because it is likely that we won’t want the UMSP card showing up on the live or legacy sites for ~ the next year. If we commented out the injector for UMSP, someone would need to remember to comment it out before every release.

@aurreco-uga will add a new property `isSecret` to the clinepi.xml file (**on Tuesday May 31 or later**) and will test to make sure it doesn’t break anything

- `isSecret = T` will allow studies to appear on the QA and QA.restricted sites, but there will be no study card (neither active nor grayed out) on the live & legacy sites
- `isSecret = F` will allow either active or grayed out study cards to appear on the live & legacy sites

_**Note, David Roos is in California this week showing ClinEpi to PRISM and UMSP providers, so please don’t push any changes before Tuesday May 31!**_

after Cristina has tested isSecret, @dmfalke and/or @jtlong3rd  will update the client, preventing any cards (active & grayed out) from showing up on the live & legacy sites

**Comment by dmfalke** [comment]
The latest approach that @aurreco-uga and I discussed is
1. Make a new presenter prop named `isSecret`, which will default to `false`
2. Use this new prop to populate a new dataset record attribute named `is_secret`
3. In the client, only include datasets with `is_secret = true` if the `showUnreleasedData` flag is `true`.

In other words, UMSP will only appear on qa.restricted.

**Comment by dmfalke** [comment]
This work is done for this on the qa site. Getting this out on the legacy site will take some time.

**Comment by dmfalke** [comment]
> This work is done for this on the qa site. Getting this out on the legacy site will take some time.

It will be on the qa site tomorrow (Sat, June 11)

**Comment by dmfalke** [comment]
Per [this slack thread](https://epvb.slack.com/archives/C0132PM1MT5/p1654884216543559), I will revert the changes related to `isSecret` and instead remove the gray cards from the homepage.

**Comment by dmfalke** [comment]
I've reverted the application code. I will wait until tomorrow (or Monday) to remove the prop from the presenter file and close this issue.

**Comment by dmfalke** [comment]
https://github.com/VEuPathDB/ClinEpiPresenters/commit/7a74b213e0829dafb72fd88043e311607436e010
