### ISSUE TITLE
Remove pages that contain download files that were previously accessed via the "data versions" table

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EbrcModelCommon#25]
We now provide access to all old versions of download files on the Download tab. However, we still have a "Data versions" table on the View Study Details tab that provides links to webpages that contain complete old download files with URLS like https://qa.restricted.clinepidb.org/ce.restricted.qa/app/downloads/release-5/0ad509829e83ba34262a068163c83c5efcc5c55a/ (PRISM, a public study). While someone clicking on the link will encounter a pop-up asking them to sign-in/submit an access request for non-public studies, a person who has the URL itself has no problem accessing the download files no matter what restriction level is implemented. 

We would like to remove both the data versions table and all the pages they redirect to.

**Comment by sweverschulman** [comment]
The link out has been removed from the Study Details page. 
![Image](https://user-images.githubusercontent.com/62298921/200014238-40d01809-f10c-4867-bf5f-6c6012dc29e3.png)

However, I am still able to click on the link above and reach the following page. 

![Image](https://user-images.githubusercontent.com/62298921/200014668-7f2a32f2-a64a-4f01-9218-0d40f07aaa77.png)

**Comment by dmfalke** [comment]
I think the systems group would have to disable access to that page.

**Comment by danicahelb** [comment]
info from @aurreco-uga 

the URLs are used by the client..

i think what we might want is to restrict access to the URLs (https://qa.restricted.clinepidb.org/ce.restricted.qa/app/downloads/) to the website client

im sure this has been discussed and decided somewhere.

**Comment by danicahelb** [comment]
Banner has been updated:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/25450900/202001414-a52c186a-b10c-4a24-912a-03025d381908.png">

access to urls is now restricted

**Comment by dmfalke** [comment]
I think this is complete, so I will close and move to **Ready for testing**
